/*
 * Danish Wasif, Evan Woo, Michael Xie, Justin Ye
 * August 24, 2021
 * ICS4UE-20
 * Tutorial.java
 * Class that displays the GUI aspects of the Tutorial and contains functions behind it.
 */

package pkg2048gui;

// Imports.
import java.awt.event.*;
import javax.swing.ImageIcon;

public class Tutorial extends javax.swing.JFrame {

    // Stores images from the project folder as ImageIcons in sequential order.
    ImageIcon a = new ImageIcon("Instructions1.png");
    ImageIcon b = new ImageIcon("Instructions2.png");
    ImageIcon c = new ImageIcon("Instructions3.png");
    ImageIcon d = new ImageIcon("Instructions4.png");
    ImageIcon e = new ImageIcon("Instructions5.png");
    ImageIcon f = new ImageIcon("Instructions6.png");
    ImageIcon g = new ImageIcon("Instructions7.png");
    ImageIcon h = new ImageIcon("Instructions8.png");
    ImageIcon i = new ImageIcon("Instructions9.png");

    /**
     * Creates new form instructionSlides
     */
    public Tutorial() {
        super("Tutorial");      // Creates label for the window.
        initComponents();       // Initializes components. 
    }

    // Function to be called to open the Tutorial.
    public void start() {
        this.setVisible(true);      // Hide the Tutorial window.
        lblDisplay.setIcon(a);      // Displays the first icon automatically on the display.
        progressBar.setValue(0);    // Set the progress bar to 0%.
    }

    int slide = 1;  // Variable used to state the position of the slides. When slide equals 2, an interactive portion begins.

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        btnNext = new javax.swing.JButton();
        lblDisplay = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 25, 0, 0));
        setMinimumSize(new java.awt.Dimension(500, 680));
        setSize(new java.awt.Dimension(500, 680));

        btnNext.setBackground(new java.awt.Color(236, 141, 83));
        btnNext.setFont(new java.awt.Font("Clear Sans", 1, 18)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("NEXT");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        btnNext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tutorial.this.keyPressed(evt);
            }
        });

        lblDisplay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tutorial.this.keyPressed(evt);
            }
        });

        btnMenu.setBackground(new java.awt.Color(245, 124, 95));
        btnMenu.setFont(new java.awt.Font("Clear Sans", 1, 18)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setText("MENU");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        btnMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tutorial.this.keyPressed(evt);
            }
        });

        progressBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tutorial.this.keyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNext)
                        .addComponent(btnMenu))
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Switches images of the tutorial on the display when the Next button is pressed.
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        switch (slide) {
            case 1:
                lblDisplay.setIcon(b);      // Sets icon to b.
                slide++;                    // Adds 1 to the slide counter.
                btnNext.setEnabled(false);  // Disable the Next button.
                progressBar.setValue(14);   // Increases the progress bar to 14%.
                break;
            // Interactive tutorial happens here. See keyPressed(java.awt.event.KeyEvent evt) for more info.
            case 2:
                lblDisplay.setIcon(d);      // Sets icon to d.
                progressBar.setValue(29);   // Increases the progress bar to 29%.
                slide++;                    // Adds 1 to the slide counter.
                break;
            case 3:
                lblDisplay.setIcon(e);      // Sets icon to e.
                progressBar.setValue(43);   // Increases the progress bar to 43%.
                slide++;                    // Adds 1 to the slide counter.
                break;
            case 4:
                lblDisplay.setIcon(f);      // Sets icon to f.
                progressBar.setValue(57);   // Increases the progress bar to 57%.
                slide++;                    // Adds 1 to the slide counter.
                break;
            case 5:
                lblDisplay.setIcon(g);      // Sets icon to g.
                progressBar.setValue(71);   // Increases the progress bar to 71%.
                slide++;                    // Adds 1 to the slide counter.
                break;
            case 6:
                lblDisplay.setIcon(h);      // Sets icon to h.
                progressBar.setValue(86);   // Increases the progress bar to 86%.
                slide++;                    // Adds 1 to the slide counter.
                break;
            case 7:
                lblDisplay.setIcon(i);      // Sets icon to i.
                progressBar.setValue(100);  // Increases the progress bar to 100%.
                btnNext.setEnabled(false);  // Disables the Next button as the user has reached the end.
                break;
        }
    }//GEN-LAST:event_btnNextActionPerformed

    // When the Menu button is pressed.
    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        this.setVisible(false);     // Closes the Tutorial window.
        Menu m = new Menu();        // Creates an object to be able to call methods from this class.
        m.start();                  // Calls on method to open the Main Menu.
    }//GEN-LAST:event_btnMenuActionPerformed

    // Method to check if the user presses the right arrow key in the interactive tutorial.
    private void keyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyPressed
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT && slide == 2) {  // If the user presses the right key, and the display is on the second slide.
            btnNext.setEnabled(true);   // Re-enable the Next button.
            lblDisplay.setIcon(c);      // Display the next image.
        }
    }//GEN-LAST:event_keyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tutorial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnNext;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDisplay;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
