/*
 * Danish Wasif, Evan Woo, Michael Xie, Justin Ye
 * August 24, 2021
 * ICS4UE-20
 * Tutorial.java
 * Class that displays the GUI aspects of the Tutorial and contains functions behind it.
 */

package pkg2048gui;

// Imports.
import java.awt.event.*;
import javax.swing.ImageIcon;

public class Tutorial extends javax.swing.JFrame {

    // Stores images from the project folder as ImageIcons.
    ImageIcon a = new ImageIcon("Instructions1.png");
    ImageIcon b = new ImageIcon("Instructions2.png");
    ImageIcon c = new ImageIcon("Instructions3.png");
    ImageIcon d = new ImageIcon("Instructions4.png");
    ImageIcon e = new ImageIcon("Instructions5.png");
    ImageIcon f = new ImageIcon("Instructions6.png");
    ImageIcon g = new ImageIcon("Instructions7.png");
    ImageIcon h = new ImageIcon("Instructions8.png");
    ImageIcon i = new ImageIcon("Instructions9.png");

    /**
     * Creates new form instructionSlides
     */
    public Tutorial() {
        super("Tutorial");
        initComponents();
    }

    public void start() {
        this.setVisible(true);
        lblDisplay.setIcon(a);
        progressBar.setValue(0);
    }

    int slide = 1;//Variable used to state the possition of the instructions, when it reaches two, an interactive portion begins

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        btnNext = new javax.swing.JButton();
        lblDisplay = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 25, 0, 0));
        setMinimumSize(new java.awt.Dimension(500, 680));
        setSize(new java.awt.Dimension(500, 680));

        btnNext.setBackground(new java.awt.Color(236, 141, 83));
        btnNext.setFont(new java.awt.Font("Clear Sans", 1, 18)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("NEXT");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        btnNext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tutorial.this.keyPressed(evt);
            }
        });

        lblDisplay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tutorial.this.keyPressed(evt);
            }
        });

        btnMenu.setBackground(new java.awt.Color(245, 124, 95));
        btnMenu.setFont(new java.awt.Font("Clear Sans", 1, 18)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setText("MENU");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        btnMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tutorial.this.keyPressed(evt);
            }
        });

        progressBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tutorial.this.keyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNext)
                        .addComponent(btnMenu))
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Method used to show the tutorial.
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        switch (slide) {
            case 1:
                lblDisplay.setIcon(b);
                slide++;
                btnNext.setEnabled(false);
                progressBar.setValue(13);
                break;
            case 2:
                lblDisplay.setIcon(d);
                progressBar.setValue(36);
                slide++;
                break;
            case 3:
                lblDisplay.setIcon(e);
                progressBar.setValue(51);
                slide++;
                break;
            case 4:
                lblDisplay.setIcon(f);
                progressBar.setValue(63);
                slide++;
                break;
            case 5:
                lblDisplay.setIcon(g);
                progressBar.setValue(76);
                slide++;
                break;
            case 6:
                lblDisplay.setIcon(h);
                progressBar.setValue(88);
                slide++;
            case 7:
                lblDisplay.setIcon(i);
                progressBar.setValue(100);
                btnNext.setEnabled(false);
                slide++;
        }
    }//GEN-LAST:event_btnNextActionPerformed

    //When the user clicks the menu button, it returns them to the main menu.
    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        this.setVisible(false);
        Menu m = new Menu();
        m.start();
    }//GEN-LAST:event_btnMenuActionPerformed

    //Method used for the user to click the right button in the interactive tutorial.
    private void keyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyPressed
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT && slide == 2) {
            btnNext.setEnabled(true);
            lblDisplay.setIcon(c);
        }
    }//GEN-LAST:event_keyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tutorial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnNext;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDisplay;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
